apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: products-ingress
spec:
  rules:
    - http:
        paths:
          - path: /actuator/prometheus
            pathType: Prefix
            backend:
              service:
                name: products-service
                port:
                  number: 8080