apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
spec:
  type: NodePort
  selector:
    app: postgres-exporter  # Seleciona os pods com o rótulo 'app: postgres-exporter'
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187
      nodePort: 32000
