apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 9090  # Porta do serviço do Prometheus
      targetPort: 9090  # Porta do contêiner do Prometheus
      nodePort: 31000  # Porta exposta em todos os nós do cluster
  selector:
    app: prometheus