apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  type: NodePort
  selector:
    app: products
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
